version: 2

jobs:
  test:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - setup_remote_docker
      - run: npm install
      - run: npm run setup
      - run: npm test

workflows:
  version: 2
  build_and_test:
    jobs:
      - test
